### ISSUE TITLE
Resolution Connection doesn't time out

### ISSUE THREAD

**Issue by tstormz** [tenbergen/Airborne-CPS#1]
I had an open resolution connection when the computer on the other end of the connection blue screened. When I started up XPlane on the machine that abruptly closed, the machine that remained on crashed with an Address already in use error (10048).

**Comment by nstemmle** [comment]
TCP timeout is around 15-30 minutes generally so you might have to wait a
long time. Restarting might work.

**Comment by andrewld3** [comment]
Issue cannot be replicated. Closing.
