### ISSUE TITLE
Add support for non-cooperative mode

### ISSUE THREAD

**Issue by William-Cook** [tenbergen/Airborne-CPS#18]
Component of Milestone 2: Add support for non-cooperative mode (no TCAS ability, no change in course or altitude). Will implement as a separate build for now, and then will be selectable as an endpoint for Andrew when he builds the menu to select options.

**Comment by William-Cook** [comment]
Added two new public functions and one private variable to the Transponder class:

```
        /*
	Changes Cooperation Mode to supplied number
	*/
	void changeCooperationMode(int mode);
	/*
	Returns Cooperation mode in effect
	*/
	int getCooperationMode();

        int cooperationMode_;
```

**Comment by William-Cook** [comment]
Modified Transponder::sendLocation() to behave differently for different cooperation modes. In Non-Cooperative Mode 1 (0 is default fully cooperative), NaN is sent for altitude to indicate to the receiving aircraft that there is no altitude data sent.

**Comment by William-Cook** [comment]
Added a private pointer to the constructing transponder (transponder_) inside each ResolutionConnection to allow for checking of Cooperation Mode.

**Comment by William-Cook** [comment]
Modified sendSense() and resolveSense() inside ResolutionConnection class to not transmit or receive Sense data in Cooperation Mode 1.

**Comment by William-Cook** [comment]
Broke something somehow and will not compile. Error messages not making a whole lot of sense. Working with Andrew now, but will resolve next time.

**Comment by tenbergen** [comment]
This was completed in Version 0.2.
