### ISSUE TITLE
Google Protocol Buffers out of Date

### ISSUE THREAD

**Issue by andrewld3** [tenbergen/Airborne-CPS#23]
Current master branch is broken. Have to reference new buffer and recompile Google's Protocol Buffer. Will refactor into code base once complete.

**Comment by andrewld3** [comment]
Video Installation will follow once bug is complete.

**Comment by tenbergen** [comment]
I remember that Google Protocol Buffer was the reason why there’s only a build for Windows x86. Can we hit two birds with one stone and switch to something that allows x64, Unix, Mac? Do only if practical.

 

 

 

__________________________________


Dr. Bastian Tenbergen
Asst. Professor for Software Engineering

Department of Computer Science
427 Shineman Center
State University of New York at Oswego
7060 State Route 104
Oswego, NY, 13126, USA
T +1 (315) 312-6605
E  bastian.tenbergen@oswego.edu
www.tenbergen.org

**Comment by andrewld3** [comment]
Possibly. I'm reading up on the protocol buffer now and have to scour the
code by hand to figure out where it's referenced at. I'll update the issue
as I find out more.

**Comment by tenbergen** [comment]
Sounds good. I’m almost 100% sure Travis and Nathan used it for something pertaining to ethernet. Start in the Transponder.

 

 

 

__________________________________


Dr. Bastian Tenbergen
Asst. Professor for Software Engineering

Department of Computer Science
427 Shineman Center
State University of New York at Oswego
7060 State Route 104
Oswego, NY, 13126, USA
T +1 (315) 312-6605
E  bastian.tenbergen@oswego.edu
www.tenbergen.org

**Comment by tstormz** [comment]
Mr Tenbergen is correct, most if not all the GPB stuff will be found in the Transponder. The Protocol Buffers are used to serialize the object before broadcasting.

**Comment by andrewld3** [comment]
Updated the GPB headers. As of right now, x64 is still not available based upon review of Google's documentation. No longer throwing GPB errors so marking as resolved.
