### ISSUE TITLE
IDE Changes Project Folder Stucture Upon Use of Another Machine

### ISSUE THREAD

**Issue by andrewld3** [tenbergen/Airborne-CPS#25]
This is a low priority issue just for reference to future developers. If any work is done on another machine, the C++ and Linker dependencies will be reassigned to that machine.

Possible Solutions:
Standardize dependency structure.
Identify the problem in the project build files.

Just be aware that Google Protocol Buffer will report out of date if the project structure changes.
No edits needed, just relink dependencies, clean project, and rebuild.

**Comment by tenbergen** [comment]
Upgraded project base to VS 2019, changed relative paths.
