### ISSUE TITLE
readme --> Cooperation with Microsoft and Laminar Research ? =)

### ISSUE THREAD

**Issue by urbanswelt** [tenbergen/Airborne-CPS#30]
Hi,
please change Microsoft to Laminar Research

--> This project is a plugin for the Microsoft X-Plane

Greetings Lars

**Comment by tenbergen** [comment]
Oops. Thanks!
Das kommt davon, wenn man Studenten die Readme schreiben laesst (und dann selber nicht mehr drauf guckt...)
