### ISSUE TITLE
IP Address Range

### ISSUE THREAD

**Issue by William-Cook** [tenbergen/Airborne-CPS#6]
TCAS gets no altitude data when IP address is out of range. Over 100 does not seem to work and lower numbers may not as well.

**Comment by andrewld3** [comment]
Issue cannot be replicated. Closing.

**Comment by tenbergen** [comment]
Bill's description was vague. I remember that this had to do with the IP Address range. Can replicate by changing IP addresses on our LAN. It's not a high priority issue - will re-open when it becomes one.
