### ISSUE TITLE
3 Connections

### ISSUE THREAD

**Issue by William-Cook** [tenbergen/Airborne-CPS#7]
When third connections joins, client with highest IP crashes.

**Comment by William-Cook** [comment]
Initial inspection of the Transponder class indicates a few clear reasons why the system cannot handle more than two clients. There may be many other things going wrong as well, as I am not terribly familiar with the Transponder class, however the Protected variables of a single Location intruderLocation and single Atomic Integer called communication indicate that the code was not written with the intention of accommodating more than one intruder. This alone would be enough to cause a crash, I believe. Will do some more investigation into the Transponder's inner workings, but it seems that surely there must at least be a set of multiple intruderLocation to accommodate more intruders. No changes made at this time, until I am certain of the variables' usages.

**Comment by William-Cook** [comment]
The Atomic<int> communication checks out. It appears somewhat unnecessary to me at this point, but I could be missing something. It is only used to indicate that the Transponder has been initialized with the start() method call. I do not believe it has bearing in this issue.

**Comment by tstormz** [comment]
The Transponder picks up other aircraft through the `receiveLocation` method which runs in a forever loop on a separate thread. When it picks up another aircraft it checks that aircraft's ID against a known set of intruders.
`Aircraft* intruder = (*intrudersMap)[intruderLocation.id()];`
if that aircraft doesn't exist it constructs a new Aircraft and adds it to the map
`(*intrudersMap)[intruder->id_] = intruder;`

Now I'm not saying it works, only that it intended to handle multiple intruders

**Comment by William-Cook** [comment]
Thanks Travis, that did help clear things up a bit.

I found something int the Transponder::recieveLocation() method that may possibly be the culprit for at least one of the problems. When a new intruder is found, at the end of the IF statement a lock is claimed for the local private aircraft_ variable. This lock is never released, and is in fact attempted to be reaquired a few lines after the end of the IF statement. I am not entirely sure why the code doesn't entirely lock up with just two aircraft because of this, but I can certainly see this potentially being the source of multi-craft problems.

if (!intruder) {
				intruder = new Aircraft(intruderLocation.id(), intruderLocation.ip());
				allocatedAircraft_.push_back(intruder);

			
				intruder->positionCurrent = updatedPosition;
				intruder->positionCurrentTime = msSinceEpoch;

				(*intrudersMap)[intruder->id] = intruder;
				**aircraft_->lock.lock();**
				ResolutionConnection* connection = new ResolutionConnection(macAddress_, 
                                          intruder->id, intruder->ip, ResolutionConnection::K_TCP_PORT, aircraft_);
				(*openConnections)[intruder->id] = connection;
			}

**Comment by William-Cook** [comment]
Apparently the lock is released within the constructor of ResolutionConnection. Adding a release statement just made the whole thing stop working properly, as would be expected. Rolling back...

**Comment by William-Cook** [comment]
New thought:

macAddress_ is defined twice in the Transponder class. It is declared in the .h file as a static string, however it is also redeclared at the top of the .cpp file without the static tag. 

```
private:
	static std::atomic<bool> initialized_;
	static std::string macAddress_;
```
```

#include "Transponder.h"

#pragma comment(lib,"WS2_32")

std::string Transponder::macAddress_ = "";
```

Is this overwriting the variable macAddress_ with the empty string, or is it creating a seperate variable in some way? I would have thought the line at the top of the .cpp file would have excluded the string declaration, or it would have been only defined in the .h file.

**Comment by William-Cook** [comment]
To elaborate, the variable is written to when the static method Transponder::getHardwareAddress() is called. This happens before the Transponder is instantiated. It is upon instantiation that the value in macAddress_ is used.

I am going to see if removing the definition at the top of the cpp file and adding the assignment of the empty string to the .h file makes any difference.

**Comment by William-Cook** [comment]
Okay, clearly my understanding of some C++ concepts are getting in the way here because Visual Studio no likey.

**Comment by William-Cook** [comment]
Added debug string printed to Log to record what the plugin sees as intruders' MAC and IP addresses. Hopefully that reveals something useful.

**Comment by William-Cook** [comment]
MAC and IP results for two OS1 and OS2 match expected results. Will need to test on OS3 when Bastian is around again, but I would venture a guess that it is not the way MAC or IP is recorded causing the issue. This narrows it down to something to do with how they are used or stored, cutting out about half of the code the bug could hide in.

**Comment by William-Cook** [comment]
Okay, with new 3-PC setup all hardwired, both the left and right machines crash when the center one boots xplane. In fact it seems that all three machines crashed.

**Comment by William-Cook** [comment]
Just before crash, all three machines see eachother as reported in log file. Right side machine's log file presents a potentially very valuable debug message at time of crash:

> ResolutionConnection::acceptIncomingIntruder - failed to bind: 10048

**Comment by William-Cook** [comment]
Middle machine also has error message prior to crash:

> ResolutionConnection::resolveSense - Failed to receive: 10054

**Comment by William-Cook** [comment]
Well it would appear this is it! Inspection of the ResolutionConnection code pertaining to those two error messages leads me to strongly believe this is where the bug is! Now I just have to figure out this networking stuff...

**Comment by William-Cook** [comment]
The bug is most certainly contained within this chunk of code.

```
SOCKET ResolutionConnection::acceptIncomingIntruder(int port)
{
	memset(&sock_, 0, sizeof sock_);
	memset(&myAddr_, 0, sizeof myAddr_);
	memset(&intruderAddr_, 0, sizeof intruderAddr_);

	sock_ = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
	if (sock_ == INVALID_SOCKET) {
		socketDebug("ResolutionConnection::acceptIncomingIntruder - socket failed to open\n", false);
		return NULL;
	}

	myAddr_.sin_family = AF_INET;
	myAddr_.sin_addr.s_addr = INADDR_ANY;
	myAddr_.sin_port = htons(K_TCP_PORT);

	int bindSuccess = bind(sock_, (struct sockaddr*)&myAddr_, sizeof(myAddr_));

	if (bindSuccess < 0) {
		char theError[32];
		sprintf(theError, "ResolutionConnection::acceptIncomingIntruder - failed to bind: %d\n", GetLastError());
		XPLMDebugString(theError);
		return NULL;
	}
```

**Comment by William-Cook** [comment]
Continued reading leads me to believe perhaps it is necessary to assign a different port to each ResolutionConnection. My understanding of Sockets is still limited to about 20 minutes of reading, but I think this may resolve the issue so I am going to try implementing it.

**Comment by William-Cook** [comment]
Need more knowledge to solve this... reading time yay

**Comment by William-Cook** [comment]
Where does intruderAddr_ get set? I can't seem to find it, and it is vital that it be different for each intruder.

**Comment by William-Cook** [comment]
Going to add a debug output to print intruderAddr_ to the log when I come back tomorrow. I do not see it ever get set, and I have a feeling thats the problem.

**Comment by tstormz** [comment]
`struct sockaddr_in intruder_addr;` is set when the socket connection is made here:
`accept_socket = accept(sock, (struct sockaddr *)&intruder_addr, &addr_len);`

http://man7.org/linux/man-pages/man2/accept.2.html
> The argument addr is a pointer to a sockaddr structure.  This
       structure is filled in with the address of the peer socket, as known
       to the communications layer.

**Comment by William-Cook** [comment]
Thanks again Travis, that helped alot. I still haven't got this fixed, but I can now rule out intruderAddr_ not being set. By the way, the code you were referencing from the main branch is not the code I am working with. You can find it under my working branch. I was able to understand what you meant though, as the only thing changed here was the naming conventions (I conformed the entire project to one standard of conventions some time back). I did however just notice this:

> src\component\ResolutionConnection.cpp(105): warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

This warning is given at compile time, and it seems relevant.

**Comment by William-Cook** [comment]
Going to try replacing the depreciated function with the recommended one. Did some reading, and it sounds like they should function almost the same way.

**Comment by William-Cook** [comment]
Too tired and stuck. Don't feel like I'm getting anywhere at the moment, however I do believe this may be a solution when better understood. Taking the last 45 minutes off to power nap before class, because I would NEVER want to fall asleep in Bastian's class.

**Comment by William-Cook** [comment]
Agreed that the 10048 is the issue, and that the problem is with the ResolutionConnection. Thank you again Travis, I have no experience when it comes to networking so this is all new to me. I am going to try and load the third instance of XPlane in a remote vicinity where acceptIncomingIntruder should not be called and see what happens, just to confirm your initial suggestion. I will then take some time to read the article you've linked before proceeding.

**Comment by William-Cook** [comment]
So I booted up one instance of XPlane in Syracuse, and when I went to boot the second machine in the usual European location it crashed every time I tried to launch it. Not sure what that is about. There is most definitely some secondary issue at work here.

**Comment by William-Cook** [comment]
Okay, for some reason it seems to be that machine is just crashing no matter what when I load XPlane

**Comment by William-Cook** [comment]
Rebooting to see if it's got a faulty version of the plugin that I forgot I loaded, but the crash has to do with missing scenery so I suspect it has nothing to do with TCAS. Will have to get this working and then try the remote 3rd plane experiment again.

**Comment by William-Cook** [comment]
Reboot solved it. Testing remote 3rd plane scenario now.

**Comment by William-Cook** [comment]
So upon loading the the third plane, both running machines saw and displayed that there was a third connection without crashing. However, when the plugin is loading, the running machine(s) always fill in the new connection's location sporadically with their own. This happens until the new connection actually loads into the world with it's own location. I believe that is due to this code inside Transponder::receiveLocation():

```
// Fill in the current values so that the aircraft will not have two wildly different position values
// If the position current is not set, position old will get set to LLA::ZERO while position current will
// be some real value, so setting the position current here prevents the LLAs from being radically different
	intruder->positionCurrent = updatedPosition;
	intruder->positionCurrentTime = msSinceEpoch;
```

This leads to the third instance crashing as soon as that happens, which is calling the ResolutionConnection::acceptIncomingIntruder() method since it has incorrect location data classifying the new plane as an intruder.

**Comment by William-Cook** [comment]
This article is super useful Travis, I believe this should clear everything up. You're right, the struct that is currently used for socket connections in ResolutionConnection is designed for single connections only, and follows the example code almost to the letter. The second section about Asynchronous Socket Programming shows a struct that uses an array of sockets. With minimal effort I think this should be implementable.

**Comment by William-Cook** [comment]
So I started making a ton of modifications to the ResolutionConnection class, but in the process I came to understand moreso how the Transponder-ResolutionConnnection interaction was intended to work with multiple clients. I deleted the changes I had made, and believe it would be wiser to follow the original intention than to hack around it. The Transponder opens and listens on a socket that is intended as the master socket, and then creates new RCs to be individual instances with their own socket for each incoming connection. Somewhere along the line, the RCs are not creating their own individual socket, but instead trying to create the same one in each instance. If I can find why that is happening, the issue should be resolved.

**Comment by William-Cook** [comment]
SOLVED! ResolutionConnection's were always being opened on the same socket number, as suspected. A static counter variable was added and used to increment the socket number opened. Three connections working beautifully now without issue! Thanks for all your help Travis!
